### ISSUE TITLE
Zero FPS crash

### ISSUE THREAD

**Issue by frafra** [NINAnor/fisk-ai#3]
```
12:08:32 log INFO Average FPS: {323.414995791479}
12:08:32 log DEBUG Set shutdown flag
12:08:32 log DEBUG Joined batch loader thread
12:08:32 log DEBUG Shutdown executor
Traceback (most recent call last):
  File "/app/app/widgets/detection_window.py", line 81, in run
    self.process_folder()
  File "/app/app/widgets/detection_window.py", line 123, in process_folder
    data_manager.add_video_data(video_path, video, self.output_folder_path)
  File "/app/app/data_manager/data_manager.py", line 144, in add_video_data
    self.get_video_duration(
  File "/app/app/data_manager/data_manager.py", line 204, in get_video_duration
    duration = frame_count / fps
ZeroDivisionError: float division by zero
````

**Comment by frafra** [comment]
I cannot reproduce the issue, since I do not have a video that make the code crash, but I implemented a more robust solution. Waiting for feedback.
