### ISSUE TITLE
"no frame!" error

### ISSUE THREAD

**Issue by frafra** [NINAnor/fisk-ai#4]
```
11:39:33 log INFO Average FPS: {310.609246484332}
11:39:33 log DEBUG Set shutdown flag
11:39:33 log DEBUG Joined batch loader thread
11:39:33 log DEBUG Shutdown executor
Downloading https://ultralytics.com/assets/Arial.Unicode.ttf to /root/.config/Ultralytics/Arial.Unicode.ttf...
100%|██████████| 22.2M/22.2M [00:00<00:00, 93.6MB/s]
Processing frames:  48%|████▊     | 588/1224 [00:41<00:46, 13.62it/s]reference overflow (pps)
Processing frames:  88%|████████▊ | 1073/1224 [01:16<00:12, 12.46it/s]deblocking_filter_idc 32 out of range
decode_slice_header error
no frame!
Processing frames:  88%|████████▊ | 1082/1224 [01:17<00:10, 13.97it/s]
Traceback (most recent call last):
  File "/app/app/widgets/detection_window.py", line 81, in run
    self.process_folder()
  File "/app/app/widgets/detection_window.py", line 121, in process_folder
    if not self.process_video(i, len(videos), video_path, data_manager):
  File "/app/app/widgets/detection_window.py", line 273, in process_video
    video_processor.cut_video(
  File "/app/app/video_processor/video_processor.py", line 309, in cut_video
    process_frame_ranges(
  File "/app/app/video_processor/video_processor.py", line 249, in process_frame_ranges
    current_frame, continue_processing = process_packet(
  File "/app/app/video_processor/video_processor.py", line 179, in process_packet
    for frame in packet.decode():
  File "av/packet.pyx", line 87, in av.packet.Packet.decode
  File "av/stream.pyx", line 172, in av.stream.Stream.decode
  File "av/codec/context.pyx", line 524, in av.codec.context.CodecContext.decode
  File "av/codec/context.pyx", line 427, in av.codec.context.CodecContext._send_packet_and_recv
  File "av/error.pyx", line 336, in av.error.err_check
av.error.InvalidDataError: [Errno 1094995529] Invalid data found when processing input; last error log: [h264] no frame!
```

**Comment by frafra** [comment]
That could be due to a corrupted file. I would try a software update before trying something else..

**Comment by frafra** [comment]
Debian updated from Bullseye to Bookworm, as well as various dependencies. Waiting for feedback.
